version: '3.8'

services:
  api:
    build: .
    container_name: mining-wave-api
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - REDIS_URL=${REDIS_URL}
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          memory: 1G
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/app
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload --log-level debug
    depends_on:
      - redis
      
  redis:
    image: redis:6.2-alpine
    container_name: mining-wave-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: