version: '3.8'

services:
  primary_db:
    image: postgres:12
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - primary_data:/var/lib/postgresql/data
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: >
      -c wal_level=replica
      -c max_wal_senders=3
      - c max_replication_slots=2
      -c hba_file=/etc/postgresql/pg_hba.conf

volumes:
  primary_data: