version: '3.8'

services:
  primary_config:
    image: postgres:13
    container_name: postgres_primary_config
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./conf:/etc/postgresql
    command: >
      /bin/bash -c "
      cp /etc/postgresql/postgresql.conf /var/lib/postgresql/data/postgresql.conf &&
      cp /etc/postgresql/pg_hba.conf /var/lib/postgresql/data/pg_hba.conf &&
      chown postgres:postgres /var/lib/postgresql/data/*.conf &&
      chmod 600 /var/lib/postgresql/data/*.conf"
    restart: "no"