version: '2.4'

services:
  primary_db:
    image: postgres:12
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REPLICATION_USER=${REPLICATION_USER}
      - SECONDARY_IP=${SECONDARY_IP}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - primary_data:/var/lib/postgresql/data
      - ./start-primary.sh:/start-primary.sh
    command: ["/bin/bash", "/start-primary.sh"]
    user: root

volumes:
  primary_data: